### ISSUE TITLE
Getting error while importing qutip since merging PR #1082

### ISSUE THREAD

**Issue by tehruhn** [qutip/qutip#1109]
Since merging PR #1082 , I've been getting this strange error whenever I import QuTiP:
```
(qutip-env) tarun@trolldem0rt:~/riken-work$ python fidel.py 
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/tarun/.pyxbld/temp.linux-x86_64-3.7/pyrex/qutip/cy/openmp/parfuncs.cpp:614:10: fatal error: src/zspmv_openmp.hpp: No such file or directory
 #include "src/zspmv_openmp.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
The codes however run fine. Here's the output from my qutip.about()

```
>>> qutip.about()

QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Original developers: R. J. Johansson & P. D. Nation.
Current admin team: Alexander Pitchford, Paul D. Nation, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, and Eric Giguère.
Project Manager: Franco Nori.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.5.0.dev0+564c987b
Numpy Version:      1.16.4
Scipy Version:      1.2.1
Cython Version:     0.29.13
Matplotlib Version: 3.1.0
Python Version:     3.7.3
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Linux (x86_64)
Installation path:  /home/tarun/riken-work/qutip/qutip
==============================================================================
Please cite QuTiP in your publication.
==============================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`

```
@nathanshammah ran this on his Mac, and had the following results.

The file runs fine on his Mac with 

- (1) conda release 4.4.1
- (2) development version 4.5.0.dev0+f77f7e4a (previous to Eric's PR merge)
- (3) updating the current development version  4.5.0.dev0+564c987b (with python setup.py develop)

The file throws an error when:
- (4) updating the current development version  4.5.0.dev0+564c987b (with python setup.py install)

Error message (then the code runs anyway):
```
(qutipdev45) nathans-mbp:Downloads nathanshammah$ python fidel.py
/Users/nathanshammah/.pyxbld/temp.macosx-10.9-x86_64-3.7/pyrex/qutip/cy/openmp/parfuncs.cpp:614:10: fatal error:
      'src/zspmv_openmp.hpp' file not found
#include "src/zspmv_openmp.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

His qutip.about(): 

```
QuTiP Version:      4.5.0.dev0+f77f7e4a (or others)
Numpy Version:      1.17.2
Scipy Version:      1.3.1
Cython Version:     0.29.13
Matplotlib Version: 3.1.1
Python Version:     3.7.4
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   True
INTEL MKL Ext:      True
Platform Info:      Darwin (x86_64)
```

Notice that in his case OPEN MP seems installed.

**Comment by tehruhn** [comment]
@Ericgig could you please take a look at this? CCing @nathanshammah again.

**Comment by Ericgig** [comment]
Hi @tehruhn, I also have the error but it does not appear when using jupyter so I missed it. The error comes from a line inside a `try` block, so I am not sure why it is not properly suppressed... I did touch much in that area so it should be a simple fix.
