### ISSUE TITLE
AttributeError: module 'pyximport.pyximport' has no attribute 'get_distutils_extension'

### ISSUE THREAD

**Issue by qci-amos** [qutip/qutip#2198]
### Bug Description

My CI builds are suddenly erroring out:

```python
../../../virtualenv/python3.8.13/lib/python3.8/site-packages/my_code.py:14: in <module>
    import qutip
../../../virtualenv/python3.8.13/lib/python3.8/site-packages/qutip/__init__.py:64: in <module>
    import qutip.cy.pyxbuilder as _pyxbuilder
../../../virtualenv/python3.8.13/lib/python3.8/site-packages/qutip/cy/pyxbuilder.py:17: in <module>
    old_get_distutils_extension = pyximport.pyximport.get_distutils_extension
E   AttributeError: module 'pyximport.pyximport' has no attribute 'get_distutils_extension'
```

### Code to Reproduce the Bug

```shell
import qutip
```

### Expected Behaviour

no exception

### Your Environment

```shell
I'm using `qutip-4.7.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`.
```

### Additional Context

This exact same environment was working in yesterday's CI build. We speculate that `Cython`'s major release [yesterday](https://pypi.org/project/Cython/#history) is related.

**Comment by qci-chen** [comment]
![image](https://github.com/qutip/qutip/assets/45803763/009a1b29-3619-4083-ac30-134259633bc9)

https://qciworkspace.slack.com/archives/CQFAJC6TT/p1689688141143989?thread_ts=1689676620.994549&cid=CQFAJC6TT

**Comment by Ericgig** [comment]
Thank you for reporting.
Yes, Qutip does not work with cython 3.0.0.
I found a bug in cython trying to fix it so the patch could take some time.

**Comment by qci-amos** [comment]
Ah, I see now that you do have a pin:
https://github.com/qutip/qutip/blob/efd39be22db0536ef0680547a6631a4f9156b922/requirements.txt#L1

but there hasn't been a release since that change.

**Comment by qci-amos** [comment]
I think this has been resolved by https://github.com/qutip/qutip/pull/2220
