### ISSUE TITLE
Tests fail: No module named 'cqobjevo_compiled_coeff_130828459648281117'

### ISSUE THREAD

**Issue by KishorSalunkhe** [qutip/qutip#1084]
Running this code
import qutip.testing as qt
qt.run()
produces an error:

Monte-carlo: Collapse terms constant (str format) ... cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9025 : overriding '/Ox' with '/O1'
cqobjevo_compiled_coeff_130828459648281117.cpp
c:\anaconda\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
   Creating library C:\Users\Quantro\.pyxbld\temp.win-amd64-3.7\Release\Users\Quantro\.pyxbld\temp.win-amd64-3.7\Release\pyrex\cqobjevo_compiled_coeff_130828459648281117.cp37-win_amd64.lib and object C:\Users\Quantro\.pyxbld\temp.win-amd64-3.7\Release\Users\Quantro\.pyxbld\temp.win-amd64-3.7\Release\pyrex\cqobjevo_compiled_coeff_130828459648281117.cp37-win_amd64.exp
Generating code
Finished generating code
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9025 : overriding '/Ox' with '/O1'
cqobjevo_compiled_coeff_8398411180025011525.cpp
c:\anaconda\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
   Creating library C:\Users\Quantro\.pyxbld\temp.win-amd64-3.7\Release\Users\Quantro\.pyxbld\temp.win-amd64-3.7\Release\pyrex\cqobjevo_compiled_coeff_8398411180025011525.cp37-win_amd64.lib and object C:\Users\Quantro\.pyxbld\temp.win-amd64-3.7\Release\Users\Quantro\.pyxbld\temp.win-amd64-3.7\Release\pyrex\cqobjevo_compiled_coeff_8398411180025011525.cp37-win_amd64.exp
Generating code
Finished generating code
Process SpawnPoolWorker-671:
Process SpawnPoolWorker-669:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Anaconda\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Anaconda\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Anaconda\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "C:\Anaconda\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "C:\Anaconda\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "C:\Anaconda\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'cqobjevo_compiled_coeff_130828459648281117'
ModuleNotFoundError: No module named 'cqobjevo_compiled_coeff_130828459648281117'

Note: I have installed qutip using pip installer

**Comment by Ericgig** [comment]
string coefficient do not work in parallel on windows. 
There are no other windows specific bug reported, so if you stick to function coefficient for time dependent system, you should be fine.

**Comment by KishorSalunkhe** [comment]
Hey,
Thanks! Since test did not continue after this point, I am not sure whether to continue to use the qutip. Is there any way to bypass these kind of errors and continue the test?

**Comment by Ericgig** [comment]
Uninstalling cython or using a virtualenv without it will make the risky code make an import error and not crash. cython is needed for installation, but mostly optional at runtime. It can be used to speedup some computations but usually the compilation time is not worth it.

Or, you can run tests per section:
```
import nose
import glob
for testfile in glob.glob(".../qutip/qutip/tests/*.py):
    test = testfile[N:-3].repace("\",".") # remove the whole path and the .py: ( "qutip.tests.test_qobj" )
    nose.run(defaultTest=test, argv=['nosetests', '-v'])
```
test_mccolve, test_stochastic_se and test_stochastic_me will fail/crash, but I expect most of the rest to pass.

**Comment by nathanshammah** [comment]
After merging #1097, the following error is given on a Linux machine from travis CI 
AttributeError: 'QobjEvo' object has no attribute 'coeff_files'
1656Exception in thread Thread-546:
1657Traceback (most recent call last):
1658  File "/Users/travis/miniconda/envs/test-environment/lib/python3.7/threading.py", line 926, in _bootstrap_inner
1659    self.run()

**Comment by rupayan2029** [comment]
I am also having this problem on 21/1/2020

**Comment by hodgestar** [comment]
We've worked on QobjEvo quite a bit since this bug was opened and in QuTiP v5 it is very different. Closing this but feel free to reopen if it occurs on either 4.7.3+ or QuTiP 5.
