### ISSUE TITLE
QuTip fails on import with numpy 1.22.1

### ISSUE THREAD

**Issue by gecrooks** [qutip/qutip#1766]
Qutip works fine with numpy 1.21.1, but fails on import with 1.22 numpy, released Dec 31st.  Tested on ubuntu and MacOS.

```
>>> import qutip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/work/miniconda3/envs/QF9/lib/python3.9/site-packages/qutip/__init__.py", line 73, in <module>
    (_blas_info() == "OPENBLAS" and platform.system() == 'Darwin')
  File "/Users/work/miniconda3/envs/QF9/lib/python3.9/site-packages/qutip/utilities.py", line 430, in _blas_info
    blas_info = config.blas_opt_info
AttributeError: module 'numpy.__config__' has no attribute 'blas_opt_info'
```

Failure occurs here,

https://github.com/qutip/qutip/blob/52d01da181a21b810c3407812c670f35fdc647e8/qutip/utilities.py#L340

which is kind of mysterious since line 339 explicitly checks that the 'blas_opt_info' attribute exists, and then fails at line 340 because the attribute doesn't exist.

**Comment by Ericgig** [comment]
It's fixed in `master` with #1752. A patch should be released soon.

**Comment by quantshah** [comment]
We should release the patch soon. @hodgestar Let me know if you need any help with the release.

**Comment by goerz** [comment]
> It's fixed in `master` with #1752. A patch should be released soon.

Please do release that patch! 😉

**Comment by hodgestar** [comment]
I'm working on a 4.6.3 release at the moment.

**Comment by hodgestar** [comment]
4.6.3 has been released.
